site_name: RTMQ README for TIQC
site_description: RTMQ README for TIQC
site_author: xiaoshe
site_url: https://xiaoshecode.github.io/rtmq/
repo_url: https://github.com/xiaoshecode/rtmq.git
repo_name: TIQC/RTMQReadme
nav:
    - Home: index.md
    - Install: 
      - SeqInstall: SeqInstall.md
      - DeviceInstall: DeviceInstall.md
    - Tutorial:
      - SeqTutorial: SeqTutorial.md
      - DeviceTutorial: DeviceTutorial.md
    - Config: 
      - SeqConfig: SeqConfig.md
      - DeviceConfig: DeviceConfig.md
    - DebugLog: DebugLog.md
    # - About: about.md
    - Test: test.md
    
theme: 
  name: material
  language: zh
  features:
    - navigation.instant # 即时加载
    - navigation.tracking # 瞄点跟踪
    # - navigation.tabs # 导航选型卡
    - navigation.tabs.sticky  #粘性导航选项卡
    # - navigation.sections  #次级目录在侧边栏中呈现为组，与tabs同存则有2级导航
    - navigation.expand #左侧边栏全展开
    - navigation.top  #返回顶端
    - search.suggest # 搜索建议
    - search.highlight # 搜索高亮
    - search.share # 搜索分享
    - header.autohide # 自动隐藏标题
  palette: #切换黑白模式
    - media: "(prefers-color-scheme: light)" 
      scheme: default  #配色方案：浅色模式
      primary: indigo  #原色，默认蓝，用于标题、侧边栏、文本链接和其他几个组件
      accent: indigo  #强调色，默认蓝，可以交互的元素如悬停链接、按钮和滚动条
      toggle:
        icon: material/weather-sunny #图标，太阳
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"  
      scheme: slate  #配色方案：深色模式
      toggle:
        icon: material/weather-night  #图标，月亮
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/git-alt  #存储库图标

edit_uri: edit/master/docs/
  

markdown_extensions:
    - abbr # 缩写
    - admonition # 警告或标注
    - pymdownx.details # 细节折叠
    - pymdownx.superfences # 代码块增强
    - pymdownx.highlight # 代码高亮
    - attr_list

plugins:
  - git-revision-date #每页底部显示文档最后更新日期，安装 pip install mkdocs-git-revision-date-plugin
  - git-revision-date-localized:  #每个页面底部添加本地化更新和创建日期，安装pip install mkdocs-git-revision-date-localized-plugin
      type: date  #日期格式，有效值为date、datetime、iso_date、iso_datetimetimeago
      fallback_to_build_date: true  #默认false，启用则回退到mkdocs build执行的时间
      enable_creation_date: true  #最后更新日期旁边显示与页面关联的文件的创建日期
